---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
    registries: "*"
    schedule:
      interval: dails
