---

name: release-please

on:
  push:
    branches: main

env:
  GEM_NAME: "semian-postgres"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ruby
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          prerelease: true
          package-name: ${{ env.GEM_NAME }}
          version-file: "lib/semian/pg/version.rb"
          command: "github-release"

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}

      - name: Build and Publish
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build ${{ env.GEM_NAME }}.gemspec -o ${{ env.GEM_NAME }}.gem
          gem push ${{ env.GEM_NAME }}.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        if: ${{ steps.release.outputs.release_created }}

  release-pr:
    runs-on: ubuntu-latest
    needs:
      - release-please
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ruby
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          package-name: ${{ env.GEM_NAME }}
          version-file: "lib/semian/pg/version.rb"
          command: "release-pr"
